# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MigraineKiller' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MigraineKiller

	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'Charts'

  target 'MigraineKillerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
